### ISSUE TITLE
CPU Load Very High

### ISSUE THREAD

**Issue by SpEcHiDe** [SpEcHiDe/wat-bridge#14]
![photo_2018-01-21_19-27-35](https://user-images.githubusercontent.com/6317196/35236237-9ae09462-ffcc-11e7-9c4b-ffb7cfa6450d.jpg)

As shown in the above screenshot, CPU Load is very high when running ```sh status.sh```

There is no issue, when running with ```python3 watbridge.py```

**Comment by necessary129** [comment]
the `status.sh` doesn't sleep, at all! It will therefore consume 100% of your CPU all the time. It would be better to put a sleep in there somewhere, like this:

```diff

diff --git a/status.sh b/status.sh
index 75facd8..3806d75 100644
--- a/status.sh
+++ b/status.sh
@@ -1,19 +1,20 @@
 #!/bin/sh
 while :
 do
 for PID in `cat log.pid`
 do
   if ps -p $PID > /dev/null
    then
      echo "$PID is running"
      # Do something knowing the pid exists,
      # i.e. the process with $PID is
      # running
      a=`grep "^\[ERROR\]" log.txt`
      if [ $? -eq 0 ]; then
        sh kill.sh
        sh run.sh
      fi
   fi
 done
+sleep 1
 done
```
