### ISSUE TITLE
Image is not transferring from Telegram

### ISSUE THREAD

**Issue by mujeebcpy** [SpEcHiDe/wat-bridge#16]
images are only transfering from whatsapp to Telegram, not working from Telegram to whatsapp.

**Comment by SpEcHiDe** [comment]
The objective behind [this](https://blog.shrimadhavuk.me/posts/2017/12/31/Telegram-WhatApp/) was to get people from WhatsApp to Telegram, and not vice versa. 

This might get added soon, depending on ___, because WhatsApp still rules the messaging world.
