### ISSUE TITLE
Old Version

### ISSUE THREAD

**Issue by PhDrevix** [SpEcHiDe/wat-bridge#21]
INFO: yowsup.common.http.warequest:{"login":"[number]","status":"fail","reason":"old_version"}

status: fail
reason: old_version
login: [number]

I tried with more numbers and I have the problem with the version

**Comment by SpEcHiDe** [comment]
Hi. Please use this. https://github.com/tgalal/yowsup/issues/2350#issuecomment-348726721

Thank you.
